### ISSUE TITLE
Console output

### ISSUE THREAD

**Issue by seanmcilvenna** [rimmartin/saxon-node#13]
The SaxonProcessor.cpp file has a cout>> that gets output every time the module is used. I'd like to request that this be removed and some options be added to specify where logging information be sent like this (preferrably not always the console)

**Comment by rimmartin** [comment]
Yea, by Monday I'll have it clean; and building on mac windows and linux

**Comment by rimmartin** [comment]
I have it for nodejs v4.2.x  Am testing 5.0.0.

For v0.12.x there i a tagged branch for which it can be done

**Comment by seanmcilvenna** [comment]
Oh great! This answers my question in https://github.com/rimmartin/saxon-node/issues/14 too :)

**Comment by rimmartin** [comment]
You in the situations your users are all nodejs versions? Back to v0.12.x or further?

I found a CentOS 5 reason to test the Excelsior JET tool for pure c++ application this week so should learn more about stability and error handling

**Comment by seanmcilvenna** [comment]
Sorry, missed this question. 0.12.x is as far back as we are targeting.

**Comment by rimmartin** [comment]
Hi @seanmcilvenna , will you need the Saxon/C 1.0.0 new api and new features back in v0.12.x branch?

**Comment by seanmcilvenna** [comment]
Hi @rimmartin , yes that would be ideal. Unfortunately, due to some other dependent modules, we aren't able to upgrade to the latest version of node.js yet... So, we are stuck with 0.12.7 until our dependent modules are fully compatible with v4.x.
