### ISSUE TITLE
First major release of Saxon/C version 1.0.0 now available

### ISSUE THREAD

**Issue by ond1** [rimmartin/saxon-node#17]
Dear All,

Following the successes of Saxon/C alpha and beta releases over the last 2 years we are pleased to say that we have released the first major release of Saxon/C version 1.0.0.
This release is only available under a Linux platform. Windows release will follow later. We hope this will fill a longstanding gap in the market for XSLT 2.0 on C/C++ based platforms.

We are now offering the the commercial products in addition to the SaxonHE under Saxon/C: Namely Saxon-HE/C, Saxon-PE/C and Saxon-EE/C. 

We have provided a PHP extension module for Saxon/C with the equivalent APIs as on C/C++.

This release has been uploaded to the Saxonica servers, which can be accessed from the following location: http://www.saxonica.com/saxon-c/index.xml 

We have made major changes to the APIs to offer feature in support of the specifications XSLT 2.0/3.0, XQuery 1.0/3.0, XPath 2.0/3.0 and Schema Validation 1.0/1.1 from C/C++ or PHP applications.
Thank you to all the users of Saxon/C Beta version 0.3.1 who provided useful feedback as we have fixed several bugs in the new release. 
It is a lot more stable and robust than previous releases therefore it has gained its major release status.

See release note :http://www.saxonica.com/saxon-c/release-notes.xml and documentation: http://www.saxonica.com/saxon-c/doc/html/index.html
PHP API: http://www.saxonica.com/saxon-c/doc/html/index.html#php-api

A note for open-source enthusiasts: the Saxon-HE/C version is open-source but requires proprietary software to build it.

Key changes: 

```
Updated the Saxon processor to the Java Saxon 9.6.0.9 version.
Improved memory handling and internal code structure both in C++ and PHP
New APIS: Support for XPath 2.0/3.0 and Schema Validation 1.0/1.1
Added XDM Data Model API in support of the specs XPath, XQuery, XSLT and Schema Validation
Improved memory handling of XDM data model and internal code structure both in C++ and PHP
Fixed several bugs issues. See: https://saxonica.plan.io/projects/saxon-c/issues filter by Fixed in version= ‘1.0.0' and status = ‘Closed'  
```

The 64-bit Linux version of Saxon/C will be released shortly. Also the Windows version will follow after. We hope to update the baseline of Saxon/C to 9.7 in due course (the code has not been forked).

kind regards,

---

O'Neil Delpratt

**Comment by rimmartin** [comment]
Thank you @ond1 !  I'll begin applying this this evening!

**Comment by rimmartin** [comment]
Hi @ond1,

Now have the api matching and compiling.  During a run with SAXONC_HOME set to export SAXONC_HOME=/home/user/Software/Saxonica/Saxon-HEC1.0.0 the dllName becomes
'xon-HEC1.0.0/saxon-data/home/user/Software/Saxonica/Saxon-HEC1.0.0/libsaxonhec.so'

line# 22 of SaxonCGlue.c

It seems to mix with resources_dir but I haven't puzzled it out fully.  Perhaps they aren't big enough dimensions.  Not sure if strncat extends dimension and my base path is longer than the default

**Comment by rimmartin** [comment]
XdmValue constructor(s) doesn't work for me anymore. Haven't found an equivalent way yet for 
```
xsltProcessor->setParameter(*pn, new XdmValue(*pnValue));
```
where *pnValue is a const char* type

http://en.cppreference.com/w/cpp/language/member_template shows templating of a member function is possible but constructors need the template on the class.

**Comment by ond1** [comment]
You have to create the Xdm Value via the SaxonProcessor. I will give you
better direction later.

**Comment by ond1** [comment]
Hi @rimmartin,


> On 11 Feb 2016, at 03:32, rimmartin <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> XdmValue constructor(s) doesn't work for me anymore. Haven't found an equivalent way yet for
> 
> xsltProcessor->setParameter(*pn, new XdmValue(*pnValue));

We changed how this is done to use the SaxonProcessor class.
See: http://www.saxonica.com/saxon-c/doc/html/classSaxonProcessor.html <http://www.saxonica.com/saxon-c/doc/html/classSaxonProcessor.html>
You have to now use one the make methods (i.e. makeStringValue) to create a XdmAtomicValue which is a subclass of XdmValue. See: http://www.saxonica.com/saxon-c/doc/html/classXdmAtomicValue.html <http://www.saxonica.com/saxon-c/doc/html/classXdmAtomicValue.html>

Also see http://www.saxonica.com/saxon-c/doc/html/classXdmValue.html <http://www.saxonica.com/saxon-c/doc/html/classXdmValue.html>

Alternatively you can create a jni jobject of a string via the C function then pass that to new XdmAtomicValue(jobject). This might be more complicated. See the files SaxonCXPath.h and SaxonCXPath.c:

jobject getJavaStringValue(sxnc_environment environ, const char *str);


> where pnValue is a const char type
> 
> http://en.cppreference.com/w/cpp/language/member_template <http://en.cppreference.com/w/cpp/language/member_template> shows templating of a member function is possible but constructors need the template on the class.
> 
> 

Not sure on the context of this to the above

**Comment by ond1** [comment]
Hi @rinmartin,


> On 10 Feb 2016, at 14:00, rimmartin <notifications@github.com <mailto:notifications@github.com>> wrote:
> Now have the api matching and compiling. During a run with SAXONC_HOME set to export SAXONC_HOME=/home/user/Software/Saxonica/Saxon-HEC1.0.0 the dllName becomes
> 'xon-HEC1.0.0/saxon-data/home/user/Software/Saxonica/Saxon-HEC1.0.0/libsaxonhec.so'
> 
> line# 22 of SaxonCGlue.c
> 
> It seems to mix with resources_dir but I haven't puzzled it out fully. Perhaps they aren't big enough dimensions. Not sure if strncat extends dimension and my base path is longer than the default
> 
> 

Maybe I got this wrong, but I cannot see the error. Would you like to file a bug and send a repo.


Thanks and kind regards,


-------------------------------
O'Neil Delpratt
Software Developer, Saxonica Limited 
Email: oneil@saxonica.com <mailto:oneil@saxonica.com>
Twitter: https://twitter.com/ond1 <https://twitter.com/ond1>
Tel: +44 118 946 5894
Web: http://www.saxonica.com <http://www.saxonica.com/>
Saxonica Community site: http://dev.saxonica.com <http://dev.saxonica.com/>
Bug tracking site: https://saxonica.plan.io/ <https://saxonica.plan.io/>

**Comment by rimmartin** [comment]
Ah nice!  wasn't looking at the right place and was a bit sleepy that evening.  Made it much harder than it now is:-) SaxonProcessor is real handy for me.

saxon-node is now pure glue; it simply compiles and links with your api where it is installed.  My original tests are working.

Will explore exposing more of your api to nodejs

Thank you @ond1 !

**Comment by seanmcilvenna** [comment]
Does the Saxon/C api have the ability to inject references?
Pseudo-code example:

```
var saxonProcessor = ...
saxonProcessor.getReferenceContent = function(reference) {
  if (reference == "test.xslt") {
    return "<xslt></xslt>";
  }
}
```

**Comment by ond1** [comment]
Hi @seanmcilvenna <https://github.com/seanmcilvenna>,

I am not sure what you mean by inject references. Please could you explain in more details what requirements you are trying to satisfy?

kind regards,

O’Neil

**Comment by rimmartin** [comment]
@seanmcilvenna, some kind of resolver?

**Comment by seanmcilvenna** [comment]
Yes, a resolver... When an XSLT <xsl:include>'s another xslt, be able to resolve that *for* saxon without saxon having to hit the file system.
