### ISSUE TITLE
Saxon/C Maintenance Release is out: Saxon/C 1.0.1

### ISSUE THREAD

**Issue by ond1** [rimmartin/saxon-node#18]
Dear All,

We have uploaded a new maintenance release of Saxon/C 1.0.1 to the Saxonica server:

http://www.saxonica.com/saxon-c/index.xml

This is the first maintenance release of the Saxon/C 1.0 series therefore there has been quite a number of bugs fixed.

See release notes: http://www.saxonica.com/saxon-c/release-notes.xml alternatively go to
https://saxonica.plan.io/projects/saxon-c/issues filter by Fixed in version= ‘1.0.0' and status = ‘Closed'.

See the Saxon/C documentation: http://www.saxonica.com/saxon-c/doc/html/index.html and the PHP API: http://www.saxonica.com/saxon-c/doc/html/index.html#php-api

We offer the the commercial products in addition to the SaxonHE under Saxon/C: Namely Saxon-HE/C, Saxon-PE/C and Saxon-EE/C.

The Windows release will follow later.

**Comment by rimmartin** [comment]
Thank you @ond1 

Putting it in use with this project.

Is there a timeline for a mac version?

**Comment by ond1** [comment]
> On 8 Apr 2016, at 12:42, rimmartin <notifications@github.com> wrote:
> 
> Is there a timeline for a mac version?


Thanks for the reminder.  Now that we got the Saxon/C maintenance release out I will be switching focus to getting the mac version out.

**Comment by rimmartin** [comment]
Great!  I have a c++ project at work that does linux, darwin and windows

**Comment by rimmartin** [comment]
Hi @ond1,

Anything I could test?  I've only got OSX 10.7 though

**Comment by ond1** [comment]
Hi Martin,

Sorry about the delays on this. I have the Saxon/C dylib library but failing to compile the C++ code at the moment. Would you like to help with this?

Hopefully I can get back on it this week.

**Comment by rimmartin** [comment]
Sure. we're both busy.  Later this week or next week

**Comment by rimmartin** [comment]
Upgraded to saxon/c v1.0.2

Tests ran that were HEC compatible.  Anyone running PEC or EEC let me know if you run into an issue

**Comment by rimmartin** [comment]
Oh, did it also for mac.

**Comment by rimmartin** [comment]
on version v1.1.2
