### ISSUE TITLE
Saxon/C Major Release is out: Saxon/C 1.1.0

### ISSUE THREAD

**Issue by ond1** [rimmartin/saxon-node#21]
**Major release version 1.1.0**

Released on 27th September 2017

This is a major Release of Saxon/C on Linux, Mac OS X and Windows. We have made a number of changes and fixed several bugs in the new release. In this release we have the following Saxon/C products: Saxon-HE/C, Saxon-PE/C and Saxon-EE/C

Documented changes in the release:

- Updated the core XSLT processor to the Java Saxon 9.8.0.4 version.

- Updated APIs: Support for XSLT 3.0, XQuery 3.1, XPath 2.0/3.0 and Schema Validation 1.0/1.1

- Added XDM Data Model API in support of the specs XPath, XQuery, XSLT and Schema Validation

- **Support for user defined functions**. Users can now write their functions in C++/PHP and invoke them in XSLT, XQuery and XPath.

- Support for PHP7 distribution

- Windows Saxon/C builds

- Updated to Excelsior Jet 11.3 (MP1) - cross compiler tool of Saxon

- Revised API for Xslt, XQuery in C, C++ and PHP

**Comment by rimmartin** [comment]
Thank you @ond1 !  Will test and make nodejs glue compatible

**Comment by julienguiraud** [comment]
Dear @rimmartin , @ond1 , 
For our project, we need Saxon-HEC 1.1.0 on NodeJS 8.9.4.
Will your release be compliant with this environment ?
Do you have a release planning ?
Thanks !

**Comment by rimmartin** [comment]
Let me test and release again.  I also think there is a windows 64 bit I can add for those users too

**Comment by rimmartin** [comment]
and will add a travis-ci matrix of builds for it

**Comment by rimmartin** [comment]
starting to build on travis for node 6, 8, 9 on mac; a yml issue for linux
https://travis-ci.org/rimmartin/saxon-node/builds/401564431

**Comment by rimmartin** [comment]
linux is good. Not compiling on mac or windows yet

**Comment by ond1** [comment]
Hi,

On mac we have resolved a bug issue which might solve your issue. Please see:

https://saxonica.plan.io/issues/3837 <https://saxonica.plan.io/issues/3837>

I hope it helps.

kind regards,

O'Neil

**Comment by rimmartin** [comment]
Hi @ond1 !
when this travis-ci build is successful it will be a good measure of state:-)  Thank you for the info

**Comment by rimmartin** [comment]
C99, there is a stdbool.h that defines bool
https://clang.llvm.org/doxygen/stdbool_8h_source.html

**Comment by ond1** [comment]
Hi,

I hit this problem. I have modified the defined variable name for bool in Saxon/C to __bool.

See bug issue: https://saxonica.plan.io/issues/3837 <https://saxonica.plan.io/issues/3837>

You can get replace the following files in your project:

https://dev.saxonica.com/repos/archive/opensource/latest9.8/hec/Saxon.C.API/HEC/SaxonCGlue.h <https://dev.saxonica.com/repos/archive/opensource/latest9.8/hec/Saxon.C.API/HEC/SaxonCGlue.h>
https://dev.saxonica.com/repos/archive/opensource/latest9.8/hec/Saxon.C.API/SaxonCProcessor.c <https://dev.saxonica.com/repos/archive/opensource/latest9.8/hec/Saxon.C.API/SaxonCProcessor.c>


This fix will be in the next maintenance release.

I am having some compatibility issue with the mac osx version 10.13 and Saxon/C which I am still investigating.

kind regards,

O'Neil

**Comment by rimmartin** [comment]
Hi, much further!  Compiles and runs all tests successfully!
The jet is taking a long time on mac and:
```
Trying to unregister a component with mounted embedded files: /Users/travis/build/rimmartin/Saxonica/Saxon-HEC1.1.0/rt/jetrt/libXCP211308121.dylib
```
https://travis-ci.org/rimmartin/saxon-node/jobs/407572766

**Comment by ond1** [comment]
Hi @rimmartin,

At the end of the tests do you call the release() function which exists in the SaxonProcessor class?

kind regards,

O'Neil

**Comment by rimmartin** [comment]
Hi @ond1,

when I turn on the call to release() the next test starts(without my process ending and restarting) and I run into 
```
JNI_CreateJavaVM() failed with result: -5
```
[restarttestmain.tar.gz](https://github.com/rimmartin/saxon-node/files/2237973/restarttestmain.tar.gz)
is pure c++ app that illustrates the problem.  I you think it is an issue I can ad it to your tracking system

**Comment by ond1** [comment]
Hi @rimmartin,

The release() call definitely needs to be the last thing you do after you have finished with Saxon/C. It can only be called once and is necessary in the cleanup of Jet before the application is to exit.

If you change: 

processor->release();
SaxonProcessor* processor2(new SaxonProcessor(true));

to the following then it should work fine:

SaxonProcessor* processor2(new SaxonProcessor(true));
processor->release();

I also tried omitting the release method and got the initial message you reported:

Trying to unregister a component with mounted embedded files.

**Comment by rimmartin** [comment]
on next version
