### ISSUE TITLE
Offer to contribute

### ISSUE THREAD

**Issue by seanmcilvenna** [rimmartin/saxon-node#6]
Hey @rimmartin,

Couldn't find your email, so will post this as an issue, and you can delete it later (or I will).
Just wanted to mention that the company @mhchristensen and I work for do a *great* deal of work in XML, and are using node.js for a couple large(ish) projects. (At least) I would like to contribute to the development of this module in any way possible. If it is a matter of spinning up various VMs to compile pre-builts on, or testing, or whatever... let me know. I'm not very good with C++ but can help wherever possible. Just let me know.

**Comment by rimmartin** [comment]
You already have/are @seanmcilvenna!  I added you as a collaborator.  Partly you may need to let me know what more glue would be useful to go back and forth to http://www.saxonica.com/saxon-c/doc/html/index.html and javascript. or what helpers would be useful on the node side?

My usage that started this is fairly basic; compile a stylesheet and run multiple xml's through.  Mine take chemical and scientific markup and produce other formats such as pdb, mol2, xyz, xmol, sdf.

I'll learn more about S3 tomorrow and see how to make it possible for you to upload to the saxon-node bucket  And I'll start github pages for this project similar to the pages I have at http://rycole.com/hdf5.node/ for my other project.

Where would you like to see the project go?

**Comment by rimmartin** [comment]
One thing looking over saxon/C I want to explore is error/exception handling.  There is a way to make them come back to the node side in a callback or throw and catch...

**Comment by seanmcilvenna** [comment]
Great! Glad to hear it! Didn't realize I was marked as a contributor...
Yah, the errors are pretty generic, currently. So, more-detailed error/exception handling will be a big +

I was just messaging @ond1 via email asking about Saxon/C development... Would be great if it could support schema validation and XPath. The libxmljs module exists, though; so we can get by for now.

I think the most useful addition to the project right now is supporting 

1) more pre-built environments. would be great to get support for node 64bit. would also love to see more builds for previous versions of node (11 and 10) for both 64 bit and 32 bit windows *and* linux.
2) an easier manual-build process... perhaps including some of the saxon and java libraries used for building directly in the git project. not sure if that raises a licensing issue, or not, though.
3) in terms of functionality... would be great to have support for providing the content to files referenced by the xslts directly from memory (like I've mentioned in https://github.com/rimmartin/saxon-node/issues/2) rather than having to depend on I/O. It seems that this is dependent on saxon/c providing this functionality as well, though; looking through their API docs I don't see any way to do this.

Excited to see this project continue. As I said, we (as a company) use XML heavily, so seeing it become better-supported in Node.JS is great!

**Comment by mhchristensen** [comment]
I'd be more than happy to help as well.  Just not sure how to contribute.  I do have a Macbook Pro with Yosemite.  So that might be useful

**Comment by rimmartin** [comment]
@mhchristensen added to collaborators
started the gh-pages branch and put up some beginning pages
http://rimmartin.github.io//saxon-node/
